///Users

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_USER_FAILED = 'SIGN_USER_FAILED';
export const SIGN_UP_USER_LOADING = 'SIGN_UP_USER_LOADING';


///login

export const lOG_IN_USER = 'lOG_IN_USER';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING';
export const LOGOUT_USER = "LOGOUT_USER"

////update profile

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";


///notes

export const ADD_NOTE = "ADD_NOTE";
export const ADD_NOTE_FAILED = "ADD_NOTE_FAILED";
export const DISPLAY_NOTES = "DISPLAY_NOTES";
export const DISPLAY_NOTES_LOADING = "DISPLAY_NOTES_LOADING";
export const DISPLAY_NOTES_FAILED = "DISPLAY_NOTES_FAILED";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const UPDATE_NOTE_FAILED = "UPDATE_NOTE_FAILED"
export const DELETE_NOTE = "DELETE_NOTE";
